config:
  # Telegram Bot Token
  Token:
  # tencentID
  SecretID:
  # tencentKey
  SecretKEY:
  # 聊天群组ID
  ChatGroup:
  # 日志群组ID
  LogsGroup:
  Father:
  Debug: False
  pageMax: 10

uptimeRobotConfig:
  apiKey:
  # monitors ID
  Wandering PaperClip 流浪回形针:
  回形针归档站|paperclip.tk:
  回形针重症监护室:
